package com.cg.dms.entities;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

//class is an entity
@Entity
public class Farmer extends AbstractUser {
	
	//Id as primary key
	//autogenerated value
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int farmerId;
	
	
	//getters and setters
	public int getFarmerId() {
		return farmerId;
	}

	public void setFarmerId(int farmerId) {
		this.farmerId = farmerId;
	}
}